### ISSUE TITLE
Make sure docs refer to correct branch of master module docs

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-reports-powertrack#16]
When cognicity-reports 2.0.x is merged with master, we need to update the [reference in cognicity-reports-powertrack README.md](https://github.com/smart-facility/cognicity-reports-powertrack/blob/2.0.x/README.md#installation) to reflect that change.

**Comment by benatwork99** [comment]
I notice the master branch is failing but the build status badge is green. I think we need all our build status badges (all current projects in Travis) to include the branch in the build status badge link. 

And we should fix the master build (JSHint issues) - I can do that.
