### ISSUE TITLE
Explanation of how to enable geolocation

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-reports-powertrack#20]
https://github.com/smart-facility/petajakarta-web/issues/100
Note this will involve tweaking the text in the power track reports module to return the web page url when the user doesn't include Geo in their tweet.

**Comment by talltom** [comment]
@matthewberryman Think this is complete as reply tweets now have Twitter cards with explanation graphics attached?

E.g.: https://twitter.com/petajkt/status/715856680924282880

**Comment by talltom** [comment]
@matthewberryman still want to keep this open?
