### ISSUE TITLE
package.json specifies jsdoc version still in alpha

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-reports-powertrack#9]
package.json specifies >= 3.3.0 <4.0.0 but 3.3.0 is not out yet, except in alpha:

npm ERR! argv "node" "/usr/local/bin/npm" "update"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.17
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: jsdoc@'>=3.3.0 <4.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.0","3.2.0-dev","3.2.0","3.2.1","3.2.2","3.3.0-alpha1","3.3.0-alpha2","3.3.0-alpha3","3.3.0-alpha4","3.3.0-alpha5","3.3.0-alpha7","3.3.0-alpha8","3.3.0-alpha9","3.3.0-alpha10","3.3.0-alpha11","3.3.0-alpha12","3.3.0-alpha13"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by benatwork99** [comment]
I've also fixed this on the cognicity-server branch.

It did not fail when using earlier versions of npm (1.4.28 was installed), I had to do an `npm update -g` to update npm then I was able to reproduce the issue on 2.1.17.

**Comment by matthewberryman** [comment]
Yes I’d noticed this after upgrading npm to 2.1.17 on the harvester—I guess it’s a bit stricter in later versions of npm.

Regards,
Dr Matthew Berryman
mobile: +61 413 458 594
